build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover-coverage'
                coverage:
                    file: 'clover-coverage'
                    format: 'clover'
